version: '3'

services:
  web:
    build: .
    container_name: web
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .env:/usr/src/app/.env
    restart: always

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    environment:
      - discovery.type=single
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - graphite